/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Native search handle. The public TypeScript adapter should keep accepting
 * raw Markdown and use the existing OKF parser/projector before crossing this
 * boundary.
 */
export declare class NativeOkfSearch {
  static fromPrepared(documents: Array<PreparedDocument>): NativeOkfSearch
  ingestPrepared(document: PreparedDocument): void
  removeDocument(identity: RemoveIdentity): boolean
  search(query: string, options?: SearchOptions | undefined | null): Array<SearchHit>
  listTypes(): Array<string>
  listDegradedDocuments(): Array<DegradedDocument>
  /**
   * Tantivy exposes the pieces needed to build completion, but not the
   * section-aware MiniSearch `autoSuggest` contract. Returning ordinary
   * search hits as suggestions would be misleading, so this spike fails
   * explicitly instead.
   */
  autoSuggest(query: string, options?: SearchOptions | undefined | null): Array<Suggestion>
}

export interface DegradedDocument {
  documentId: string
  path: string
  diagnostics: Array<Diagnostic>
}

export interface Diagnostic {
  code: string
  message: string
  field?: string
  path: string
}

export interface PreparedDocument {
  documentId: string
  path: string
  type: string
  conformance: string
  diagnostics: Array<Diagnostic>
  sections: Array<PreparedSection>
}

/** Search-independent output from the existing OKF parser/projector. */
export interface PreparedSection {
  sectionId: string
  documentId: string
  conformance: string
  title: string
  path: string
  type: string
  tags: Array<string>
  status?: string
  staleAfterEpoch?: number
  stalenessClassified: boolean
  trustTier?: string
  resource: string
  headingPath: string
  description: string
  sourceText: string
  text: string
  startLine: number
  endLine: number
}

export interface RemoveIdentity {
  documentId: string
  path: string
}

export interface SearchBoost {
  resource?: number
  title?: number
  heading?: number
  description?: number
  tags?: number
  type?: number
  sources?: number
  body?: number
}

export interface SearchHit {
  documentId: string
  title: string
  sectionId: string
  score: number
  conformance: string
  matchedFields: Array<string>
  headingPath: string
  path: string
  startLine: number
  endLine: number
  snippet: string
}

export interface SearchOptions {
  limit?: number
  where?: SearchWhere
  asOf?: Date
  match?: string
  fields?: Array<string>
  boost?: SearchBoost
  fuzzy?: boolean | number
}

export interface SearchWhere {
  types?: Array<string>
  tagsAny?: Array<string>
  statuses?: Array<string>
  trustTiers?: Array<string>
  stale?: boolean
  conformance?: Array<string>
}

export interface Suggestion {
  suggestion: string
  terms: Array<string>
  score: number
}
